# Generated by Django 5.2.11 on 2026-02-07 17:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyzedListing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("url_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("platform", models.CharField(default="naukri", max_length=20)),
                ("job_title", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                (
                    "ghost_score",
                    models.IntegerField(help_text="Composite score 0-100, computed server-side from category weights"),
                ),
                (
                    "category_scores",
                    models.JSONField(
                        help_text="Per-category scores: ghost_signals, scam_signals, toxic_culture, market_reality"
                    ),
                ),
                ("red_flags", models.JSONField(help_text="Array of {category, signal, severity, explanation}")),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("apply_confidently", "Apply Confidently"),
                            ("apply_with_caution", "Apply with Caution"),
                            ("likely_fake", "Likely Fake"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ai_model_used", models.CharField(max_length=50)),
                ("tokens_used", models.IntegerField(default=0)),
                ("response_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analyzed_listings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["content_hash"], name="idx_content_hash"),
                    models.Index(fields=["created_at"], name="idx_created_at"),
                ],
            },
        ),
        migrations.CreateModel(
            name="APIUsageLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("device_hash", models.CharField(db_index=True, max_length=64)),
                ("ip_address", models.GenericIPAddressField()),
                ("endpoint", models.CharField(max_length=50)),
                ("was_cached", models.BooleanField(default=False)),
                ("response_ms", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_usage_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["device_hash", "created_at"], name="idx_device_date"),
                    models.Index(fields=["ip_address", "created_at"], name="idx_ip_date"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[("confirmed_real", "Confirmed Real"), ("confirmed_fake", "Confirmed Fake")],
                        max_length=20,
                    ),
                ),
                ("device_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="analysis.analyzedlisting",
                    ),
                ),
            ],
            options={
                "db_table": "user_feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
