# Generated by Django 5.2.11 on 2026-02-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedlisting',
            name='signals_checked',
            field=models.IntegerField(default=0, help_text='Total signals evaluated by the LLM'),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='model_used',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='apiusagelog',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyzedlisting',
            name='url_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
