# Generated by Django 5.2.11 on 2026-02-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_add_signals_checked_and_usage_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userfeedback',
            constraint=models.UniqueConstraint(fields=('analysis', 'device_hash'), name='unique_feedback_per_device'),
        ),
    ]
